"""empty message

Revision ID: 60466e54f6c5
Revises: e2c86ad35888
Create Date: 2021-04-28 21:15:55.874782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60466e54f6c5'
down_revision = 'e2c86ad35888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('type_pet', sa.String(length=250), nullable=False),
    sa.Column('sex', sa.String(length=250), nullable=False),
    sa.Column('age', sa.String(length=250), nullable=False),
    sa.Column('history', sa.String(length=250), nullable=False),
    sa.Column('behaviour', sa.String(length=250), nullable=False),
    sa.Column('breed', sa.String(length=250), nullable=False),
    sa.Column('size', sa.String(length=250), nullable=False),
    sa.Column('other', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adopt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=250), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('telephone', sa.String(length=250), nullable=True),
    sa.Column('mobile_phone', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('user_adm', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'user', ['password'])
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'username')
    op.drop_column('user', 'user_adm')
    op.drop_table('adopt')
    op.drop_table('pet')
    # ### end Alembic commands ###
